; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_extra_dirs = D:\DhanushkaC\Documents\Arduino\libraries
lib_ldf_mode = deep
monitor_speed = 115200
#monitor_port = auto 
monitor_filters = esp32_exception_decoder
board_build.partitions = default.csv
board_build.filesystem = spiffs
; MQTT_MAX_PACKET_SIZE = MQTT_RX_PAYLOAD_MAX(1200) + topic(~40) + MQTT framing(~5) + headroom
; --- Force system mode at compile time (remove flag for production) ---
; 0=CONFIG_MODE  1=NOMAL_MODE_WIFI  2=NOMAL_MODE_NO_WIFI
build_flags = -D MQTT_MAX_PACKET_SIZE=1280
    -D FORCE_SYS_MODE=1
-d config_arduino_loop_stack_size = 8192
-d config_async_tcp_stack_size = 18000
upload_flags = 
lib_deps = 
	ottowinter/ESPAsyncWebServer-esphome @^3.0.0
	arduino-libraries/NTPClient@^3.2.1
	adafruit/Adafruit NeoPixel@^1.11.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^6.21.3
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	fbiego/ESP32Time@^2.0.4
	sui77/rc-switch@^2.6.4
	me-no-dev/AsyncTCP @ 1.1.1
	adafruit/Adafruit ADS1X15@^2.6.2
